version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - docker -v
#      - java -version
#      - mvn clean install -DskipTests
artifacts:
  files:
    - 'target/service.jar'

