version: 0.2

env:
  parameter-store:
    DOCKER_PASSWORD: "/CodeBuild/DOCKER_PASSWORD"
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  build:
    commands:
      - mvn clean package docker:build -DskipTests
  pre_build:
    commands:
      - docker push mihir83in/currencyconverter
      - docker logout
