version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - java -version
      - mvn clean package docker:build -DskipTests
artifacts:
  files:
    - 'target/service.jar'

