version: 0.2

env:
  parameter-store:
    DOCKER_PASSWORD: "/CodeBuild/DOCKER_PASSWORD"
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo $DOCKER_EMAIL
      - echo $DOCKER_USERNAME
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - java -version
      - mvn clean package docker:build -DskipTests
      - docker push mihir83in/currencyconverter
      - docker logout
artifacts:
  files:
    - 'target/service.jar'

