management:
  context-path: /management
feign:
  hystrix:
    enabled: false

spring:
  cache:
    cache-names: currencies
    caffeine:
      spec: expireAfterWrite=30s
  h2:
    console:
      enabled: true
  dataSource:
    url: jdbc:h2:mem:currency;DB_CLOSE_DELAY=-1;

