management:
  context-path: /management
feign:
  hystrix:
    enabled: false

ribbon:
  eureka:
    enabled: false

server:
  port: ${PORT:8080}

spring:
  cache:
    cache-names: currencies
    caffeine:
      spec: expireAfterWrite=30s
  dataSource:
    url: jdbc:h2:mem:currency;DB_CLOSE_DELAY=-1;

