sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
script: mvn clean package -DskipTests=true
after_success:
  - docker build -t mp/currencyConverter .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mp/currencyConverter
